# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a5031adfad3736b1ce6f4bab592cac2aff429772c692cf22ce062154c01dd97e839ab05cd9d551df41fa12cd47c6ce50d815a8aee35d9a36f12e6da7875970

test:
  secret_key_base: 0f667d98e92d5fa0f3337c628ebec94aea0eed3ce71f5671a5cfb3f1da7b2c40916ac7828dcc859be5750058fd1ea6f1fb052dffec8ed060c09ae8b840ed4275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
